---
title: "Bitácora ()"
author: Pedro J. Pérez
date: "Marzo de 2021 (actualizado el `r format(Sys.time(), '%d %B %Y')`)"
output:
  html_document:
    css: !expr here::here("assets", "bitacora.css")  
    theme: paper
    highlight: textmate
    self_contained: yes
    number_sections: no
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
---

```{r chunk_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE, 
                      cache = FALSE, cache.path = "/caches/", comment = "#>",
                      #fig.width = 7, fig.height= 7,   
                      #out.width = 7, out.height = 7, 
                      # fig.asp = 7/9, out.width = "60%",  (lo q yo usaba)
                      collapse = TRUE,  fig.show = "hold",
                      fig.asp = 0.618, fig.width = 6, out.width = "70%", fig.align = "center")
```

```{r, echo = FALSE, message = FALSE}
options(scipen = 999) #- quitar notación científica
options("yaml.eval.expr" = TRUE)  #- pa que no se queje el yaml de evaluar expr: https://github.com/viking/r-yaml/issues/47
library(tidyverse)
```

--------------------------------------

El objetivo del Rproject es ... 

--------------------------------------

# Intro

