---
title: "Intro"
subtitle: ""  
author: 
  - "Pedro J. Pérez"
  #- "2021, abril"
date: "(actualizadas en `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    self_contained: true
    seal: false   #- puedes tunear la primera página de las slides    
    lib_dir: libs
    css: 
      - xaringan-themer.css
      - assets/slides_verdes.css  #- good (funciona lo de justify)
    nature:
      highlightStyle: github  #- solarized-light ; googlecode
      highlightLines: true
      highlightLanguage: ["r"]
      countIncrementalSlides: false
      ratio: "16:9"
    includes:
      #after_body: [css/insert-logo.html]
      in_header: 
        - !expr here::here("assets", "favicon-yo.html") 
        #- !expr here::here("assets", "google-analytics.html") 
#      in_header: ["favicon-yo.html", "google-analytics.html"]
---

```{r xaringan-extra, include = FALSE}
xaringanExtra::use_xaringan_extra(c("tile_view", "logo", "tachyons", "animate_css", "scribble"))
#xaringanExtra::use_share_again()
xaringanExtra::use_clipboard()
xaringanExtra::use_fit_screen()
xaringanExtra::use_tile_view()
xaringanExtra::use_tachyons()
xaringanExtra::use_extra_styles(hover_code_line = TRUE, mute_unhighlighted_code = FALSE)
xaringanExtra::use_panelset()
```

```{r xaringan-themer, include = FALSE, warning = FALSE}
library(xaringanthemer)
style_mono_light(
  base_color = "#1c5253", 
  colors = c(red = "#f34213", purple = "#3e2f5b", orange = "#ff8811", 
             green = "#136f63", white = "#FFFFFF", base = "#1c5253",
             gray = "#708090", salmon = "#ff8c69", indianred = "#cd5c5c"),
  link_color = "steelblue",
  #header_font_google = google_font("Josefin Sans"),  #- https://fonts.google.com/
  #text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono"))
```

```{r chunk-setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE,
                      #results = "hold",
                      cache = FALSE, cache.path = "/caches/", comment = "#>",
                      #fig.width = 7, #fig.height= 7,
                      #out.width = 7, out.height = 7,
                      collapse = TRUE,  fig.show = "hold", fig.retina = 4,
                      fig.asp = 7/9, out.width = "95%", fig.align = "center")
options(scipen = 999) #- para quitar la notación científica
#- para mejorar los gráficos, bueno en realidad para que se vean igual en distintos SO
#- https://www.jumpingrivers.com/blog/r-knitr-markdown-png-pdf-graphics/
knitr::opts_chunk$set(dev = "png", dev.args = list(type = "cairo-png"))
#options(htmltools.dir.version = FALSE) #- lo pongo en setup
#xaringan::inf_mr() 
```

```{r, include = FALSE}
library(flipbookr)
library(tidyverse)
```

```{css, include = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}
@media print {
  .has-continuation {
    display: block;
  }
```


class: inverse, center, middle

<br>

## `r rmarkdown::metadata$title`

#### (`r rmarkdown::metadata$subtitle`)

<br>

### `r rmarkdown::metadata$author`

#### 2021, abril

###### (actualizadas el `r format(Sys.time(), '%d-%m-%Y')`)

<br><br>
#### e-mail: [`r icon::fa("envelope")`](mailto:pedro.j.perez@uv.es) [pedro.j.perez@uv.es](mailto:pedro.j.perez@uv.es)

#### Web del curso: [`r icon::fa("link")`](https://perezp44.github.io/intro-ds-20-21-web/) https://perezp44.github.io/intro-ds-20-21-web/

```{r echo = FALSE}
xaringanExtra::style_share_again(share_buttons = c("twitter", "linkedin", "pocket") )
```

---
